version: '3.7'

services:
  httpd:
    build:
      context: ./build/python
      args:
        WEB_USER_ID: ${WEB_USER_ID}
        WEB_GROUP_ID: ${WEB_GROUP_ID}
        WEB_HOME_DIR: ${WEB_HOME_DIR}
        DEV: ${DEV}
        PROJECT_NAME: ${PROJECT_NAME}
    user: "${WEB_USER_ID}:${WEB_GROUP_ID}"
    volumes:
      - ./www-data:${WEB_HOME_DIR}
    working_dir: ${WEB_HOME_DIR}
    links:
      - mysql
    command: >
      sh -c "python manage.py runserver 0.0.0.0:80"

  mysql:
    image: mysql:8
    env_file: .env
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  default:
    external: true
    name: a_default
